import { createContext, useContext, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Languages } from 'lucide-react';

const he: Record<string, string> = {
  'Features': 'אפשרויות', 'About': 'אודות', 'Contact': 'יצירת קשר', 'Sign In': 'כניסה', 'Sign Up': 'הרשמה', 'Get Started': 'בואו נתחיל', 'Forms Area': 'אזור הטפסים', 'Menu': 'תפריט',
  'Drag & Drop Form Builder': 'בניית טפסים בגרירה', 'Build Beautiful': 'יוצרים טפסים', 'Forms Easily': 'יפים בקלות',
  'Create stunning forms with our drag & drop builder. Customize designs, add fields, and share with your team in seconds.': 'צרו טפסים מרהיבים בגרירה, התאימו את העיצוב, הוסיפו שאלות ושתפו עם הצוות.',
  'Start Building Free': 'התחילו ליצור בחינם', 'See Features': 'גלו את האפשרויות', 'Field Types': 'סוגי שדות', 'Customizable': 'ניתן להתאמה', 'To Start': 'להתחלה', 'Collaboration': 'שיתוף פעולה', 'Free': 'חינם', 'Team': 'צוות',
  'Powerful Features': 'אפשרויות מתקדמות', 'Powerful ': 'אפשרויות ', 'Everything you need to create, customize, and manage beautiful forms.': 'כל מה שצריך כדי ליצור, לעצב ולנהל טפסים יפים.',
  'Drag & Drop Builder': 'עורך בגרירה', 'Intuitive drag and drop interface to create forms in minutes without any coding.': 'ממשק גרירה נוח ליצירת טפסים תוך דקות, ללא קוד.',
  'Custom Design': 'עיצוב אישי', 'Change colors, fonts, and styles to match your brand with our design customization tools.': 'התאימו צבעים, גופנים וסגנונות למותג שלכם.',
  'Advanced Field Types': 'סוגי שאלות מתקדמים', 'Text, email, number, textarea, checkboxes, date pickers, file uploads, dropdowns, and more.': 'טקסט, אימייל, מספר, סימון, תאריך, העלאת קבצים, דירוג ועוד.',
  'Date & File Fields': 'תאריך וקבצים', 'Built-in date pickers and file upload fields for collecting any type of data.': 'שדות תאריך והעלאת קבצים לאיסוף כל המידע הדרוש.',
  'Save & Export': 'שמירה וייצוא', 'Save your forms to the cloud and access them from anywhere, anytime.': 'שמרו טפסים בענן וגשו אליהם בכל מקום ובכל זמן.',
  'Team Collaboration': 'עבודה בצוות', 'Invite team members to edit forms together with role-based permissions.': 'הזמינו חברי צוות לערוך טפסים יחד לפי הרשאות.',
  'About FormFlow': 'על CrazyForums', "We're on a mission to make form creation effortless and beautiful for everyone.": 'המטרה שלנו היא להפוך יצירת טפסים לפשוטה ונגישה לכולם.',
  'Our Mission': 'המשימה שלנו', 'To empower creators with intuitive tools that transform ideas into stunning, functional forms in minutes.': 'לתת ליוצרים כלים פשוטים להפוך רעיונות לטפסים שימושיים בתוך דקות.',
  'Our Team': 'הצוות שלנו', 'A passionate team of designers and developers dedicated to crafting the best form-building experience.': 'צוות מעצבים ומפתחים שמקדיש את עצמו לחוויית יצירת טפסים מעולה.',
  'Our Vision': 'החזון שלנו', 'To become the go-to platform for anyone who needs beautiful, powerful forms without complexity.': 'להיות הבית של מי שצריך טפסים חזקים ויפים ללא מורכבות.',
  'Start building forms today': 'התחילו ליצור טפסים היום', 'Ready to Create': 'מוכנים ליצור', 'Your First Form?': 'את הטופס הראשון?', 'Sign up for free and start building beautiful, customizable forms in minutes.': 'הירשמו בחינם וצרו טפסים יפים ומותאמים אישית תוך דקות.', 'Get Started Free': 'התחילו בחינם', 'Talk to Sales': 'דברו איתנו',
  'Loading...': 'טוען...', 'Settings': 'הגדרות', 'Sign Out': 'התנתקות', 'My Forms': 'הטפסים שלי', 'Create Form': 'יצירת טופס', 'Create Your First Form': 'יצירת הטופס הראשון', 'No forms yet': 'אין עדיין טפסים', 'Create your first form to get started': 'צרו את הטופס הראשון שלכם', 'No description': 'אין תיאור', 'Open': 'פתוח', 'Closed': 'סגור', 'Pending Invites': 'הזמנות ממתינות', 'Shared With Me': 'טפסים ששותפו איתי', 'Accept': 'אישור', 'Editor': 'עורך', 'Viewer': 'צופה', 'Unknown Form': 'טופס לא ידוע', 'Untitled Form': 'טופס ללא שם',
  'Preview': 'תצוגה מקדימה', 'Design': 'עיצוב', 'Responses': 'תשובות', 'Save': 'שמירה', 'Saving...': 'שומר...', 'Save*': 'שמירה*', 'Desktop view': 'תצוגת מחשב', 'Tablet view': 'תצוגת טאבלט', 'Mobile view': 'תצוגת טלפון', 'You have view-only access to this form': 'יש לך הרשאת צפייה בלבד בטופס', 'Share your form with others': 'שתפו את הטופס עם אחרים', 'Share Form': 'שיתוף הטופס',
  'Fields': 'שדות', 'Add': 'הוספה', 'Section': 'מקטע', 'Text Input': 'טקסט קצר', 'Email': 'אימייל', 'Number': 'מספר', 'Text Area': 'טקסט ארוך', 'Checkbox': 'תיבת סימון', 'Multiple Choice': 'בחירה מרובה', 'Date Picker': 'תאריך', 'Image': 'תמונה', 'File Upload': 'העלאת קובץ', 'Dropdown': 'רשימה נפתחת', 'Radio Buttons': 'בחירה יחידה', 'Rating Slider': 'דירוג',
  'Field Settings': 'הגדרות שדה', 'Label': 'כותרת', 'Placeholder': 'טקסט לדוגמה', 'Required': 'שדה חובה', 'Options': 'אפשרויות', 'New option': 'אפשרות חדשה', 'Minimum': 'מינימום', 'Maximum': 'מקסימום', 'Maximum must be greater than minimum (up to 100).': 'המקסימום חייב להיות גדול מהמינימום (עד 100).',
  'Form Design': 'עיצוב הטופס', 'Form Title': 'שם הטופס', 'Description': 'תיאור', 'Describe your form...': 'תארו את הטופס...', 'Background Color': 'צבע רקע', 'Background Media': 'רקע תמונה או וידאו', 'Upload File': 'העלאת קובץ', 'Apply': 'החלה', 'Cancel': 'ביטול', 'Uploading...': 'מעלה...', 'Add a background image, video, or YouTube video': 'הוסיפו תמונה, וידאו או סרטון YouTube כרקע', 'Gradient Direction': 'כיוון מעבר צבע', 'Gradient End Color': 'צבע סיום', 'Primary Color': 'צבע ראשי', 'Font Family': 'גופן', 'Form Logo': 'לוגו הטופס', 'Submit Button Text': 'טקסט כפתור השליחה', 'Success Message': 'הודעת הצלחה', 'Closed Form Message': 'הודעה לטופס סגור', 'Submit': 'שליחה',
  'No Gradient': 'ללא מעבר צבע', 'Down': 'למטה', 'Up': 'למעלה', 'Right': 'ימינה', 'Left': 'שמאלה', 'Diagonal Down-Right': 'אלכסון למטה ימינה', 'Diagonal Down-Left': 'אלכסון למטה שמאלה', 'Diagonal Up-Right': 'אלכסון למעלה ימינה', 'Diagonal Up-Left': 'אלכסון למעלה שמאלה',
  'Form Preview': 'תצוגת הטופס', 'Open in New Tab': 'פתיחה בלשונית חדשה', 'Refresh': 'רענון', 'Loading responses...': 'טוען תשובות...', 'No responses yet': 'אין עדיין תשובות', 'Responses will appear here when people submit the form': 'תשובות יופיעו כאן לאחר שליחת הטופס', 'Empty': 'ריק',
  'Back': 'חזרה', 'Login': 'כניסה', 'Go Home': 'לדף הבית', 'Form Closed': 'הטופס סגור', 'Form Not Found': 'הטופס לא נמצא', "This form doesn't exist.": 'הטופס הזה אינו קיים.', 'This form is currently closed.': 'הטופס סגור כעת.', 'Thank you! Your form has been submitted successfully.': 'תודה! הטופס נשלח בהצלחה.', 'This form has no fields yet.': 'אין עדיין שאלות בטופס.', 'Progress': 'התקדמות', 'completed': 'הושלמו', 'Select an option': 'בחרו אפשרות', 'Check this option': 'סמנו אפשרות זו', 'Drop files here or click to upload': 'גררו קובץ לכאן או לחצו להעלאה', 'Preview Mode': 'מצב תצוגה מקדימה', 'Drag and drop fields here': 'גררו שאלות לכאן',
  'Form Link': 'קישור לטופס', 'Invite by email': 'הזמנה באימייל', 'Send Invitation': 'שליחת הזמנה', 'Collaborators': 'שותפים', 'Copy': 'העתקה',
  'Welcome Back': 'ברוכים השבים', 'Create Account': 'יצירת חשבון', 'Forgot Password': 'שכחתם סיסמה?', 'Set New Password': 'הגדרת סיסמה חדשה', 'Sign in to continue building forms': 'התחברו כדי להמשיך ליצור טפסים', 'Sign up to start building forms': 'הירשמו כדי להתחיל ליצור טפסים', 'Enter your email to receive a reset link': 'הזינו אימייל כדי לקבל קישור לאיפוס', 'Enter your new password': 'הזינו סיסמה חדשה', 'Continue': 'המשך', 'Update Password': 'עדכון סיסמה', 'Back to home': 'חזרה לדף הבית', 'Your Name': 'השם שלך', 'Password': 'סיסמה', 'New Password': 'סיסמה חדשה', 'Confirm Password': 'אימות סיסמה', 'Confirm New Password': 'אימות הסיסמה החדשה', 'Forgot password?': 'שכחתם סיסמה?', 'Remember your password?': 'נזכרתם בסיסמה?', "Don't have an account? ": 'אין לכם חשבון? ', 'Already have an account? ': 'כבר יש לכם חשבון? ', 'This name is already taken': 'השם הזה תפוס', 'This name is available!': 'השם הזה פנוי!',
  'Back to Dashboard': 'חזרה לטפסים', 'Profile Settings': 'הגדרות פרופיל', 'Manage your account settings and preferences': 'ניהול הגדרות החשבון', 'Your email address cannot be changed.': 'לא ניתן לשנות את כתובת האימייל.', 'Display Name': 'שם תצוגה', 'Enter your display name': 'הזינו שם תצוגה', 'Save Display Name': 'שמירת שם', 'Change Password': 'שינוי סיסמה', 'Update your password to keep your account secure': 'עדכנו את הסיסמה כדי לשמור על החשבון', 'Enter new password': 'הזינו סיסמה חדשה', 'Confirm new password': 'אמתו את הסיסמה החדשה', 'Delete Account': 'מחיקת חשבון', 'Delete My Account': 'מחיקת החשבון שלי', 'Permanently delete your account and all associated data. This action cannot be undone.': 'מחיקת החשבון וכל המידע שלו לצמיתות. פעולה זו בלתי הפיכה.', 'Are you absolutely sure?': 'האם אתם בטוחים לחלוטין?', 'All your forms': 'כל הטפסים שלכם', 'All form responses': 'כל התשובות לטפסים', 'Your profile information': 'פרטי הפרופיל שלכם', 'Return to Home': 'חזרה לדף הבית', 'Oops! Page not found': 'אופס! הדף לא נמצא',
  'עדכוני האתר': 'Site updates', 'מה חדש?': "What's new?", 'העדכונים האחרונים והשיפורים באתר': 'Latest site updates and improvements', 'פרסם עדכון חדש': 'Publish update', 'ערוך עדכון': 'Edit update', 'עדכון חדש': 'New update', 'כותרת העדכון': 'Update title', 'תוכן העדכון...': 'Update content...', 'מעלה...': 'Uploading...', 'הוסף תמונה/סרטון': 'Add image/video', 'שמור שינויים': 'Save changes', 'פרסם': 'Publish', 'אין עדכונים עדיין. פרסם את העדכון הראשון!': 'No updates yet. Publish the first one!',
  'קישורים': 'Links', 'קישורים שימושיים': 'Useful links', 'הוסף קישור': 'Add link', 'ערוך קישור': 'Edit link', 'קישור חדש': 'New link', 'שם הקישור': 'Link name', 'שמור': 'Save', 'הוסף': 'Add', 'אין קישורים עדיין. הוסף את הקישור הראשון!': 'No links yet. Add the first one!', 'הקודם': 'Previous', 'הבא': 'Next', 'אישור': 'Confirm', '← חזור': '← Back', 'לחץ לבחירת תמונה': 'Click to choose an image', 'איך תרצה להוסיף תמונה?': 'How would you like to add an image?', 'קישור URL': 'URL link', 'העלאת קובץ': 'Upload file',
};

interface LanguageContextValue { language: 'en' | 'he'; setLanguage: (language: 'en' | 'he') => void; t: (text: string) => string; }
const LanguageContext = createContext<LanguageContextValue>({ language: 'en', setLanguage: () => {}, t: text => text });
export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'he'>(() => localStorage.getItem('crazyforums-language') === 'he' ? 'he' : 'en');
  useEffect(() => {
    localStorage.setItem('crazyforums-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
  }, [language]);
  const t = (text: string) => language === 'he' ? (he[text] || text) : (/^[\u0590-\u05ff]/.test(text) ? (he[text] || text) : text);
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>
    {children}
    <div className="fixed bottom-4 start-4 z-[70] rounded-md border border-border bg-background/90 p-1 shadow-lg backdrop-blur-md flex items-center gap-1" role="group" aria-label={language === 'he' ? 'שפת האתר' : 'Site language'} dir="ltr">
      <Languages className="w-4 h-4 text-primary mx-1" aria-hidden="true" />
      <Button size="sm" variant={language === 'en' ? 'secondary' : 'ghost'} className="h-7 px-2 text-xs" onClick={() => setLanguage('en')} aria-pressed={language === 'en'}>EN</Button>
      <Button size="sm" variant={language === 'he' ? 'secondary' : 'ghost'} className="h-7 px-2 text-xs" onClick={() => setLanguage('he')} aria-pressed={language === 'he'}>עב</Button>
    </div>
  </LanguageContext.Provider>;
};
